<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <RootNamespace>Lab_5_zadania</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="File5.fs" />
    <Compile Include="File4.fs" />
    <Compile Include="File3.fs" />
    <Compile Include="File2.fs" />
    <Compile Include="File1.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
